# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Pricels
tagline:          'A Jekyll theme'
description:      'Follow. Analyze. Report. Our goal is to track anything with a Price Tag. Easy to Use. Data updated daily. 15 Day Free Silver Membership Trial Available. Follow us on Twitter <a href="https://twitter.com/PricelsCom" target="_blank">@PricelsCom</a>.'
url:              http://about.pricels.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
