# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Pricels
tagline:          'Our Data is Pricels'
description:      'Follow. Analyze. Report. We track anything on the internet with a price tag. Easy to Use. Data updated daily. Free Trial Available. Follow us on Twitter <a href="https://twitter.com/PricelsCom" target="_blank">@PricelsCom</a>.'
url:              http://about.pricels.com
baseurl:          /

author:
  name:           'Michael Bastos'
  url:            https://twitter.com/bastosmichael

paginate:         5

# Custom vars
version:          0.1

github:
  repo:           https://github.com/pricels
