# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Michael Bastos
tagline:          'Online Resume and Blog'
description:      'Self & University taught Engineer, Data Scientist & Former Marine working as a Chief Technology Officer in San Diego. Follow me on Twitter <a href="https://twitter.com/bastosmichael" target="_blank">@bastosmichael</a> or <a href="https://www.facebook.com/michaelbastos" target="_blank">Facebook</a>.'
url:              https://michaelbastos.com
baseurl:          /

author:
  name:           'Michael Bastos'
  url:            https://twitter.com/bastosmichael

paginate:         5

# Custom vars
version:          0.1

github:
  repo:           https://github.com/bastosmichael

gems:
  - jekyll-sitemap
